### PR TITLE
Rename KASSERT_ASSERTION_ENABLED to KASSERT_ENABLED

### PR DESCRIPTION
**Pull request by DanielSeemaier**
`KASSERT_ASSERTION_` looks a bit redundant for such an important macro.

### CODE REVIEW

**Comment by Hespian** [comment]
Maybe `KASSERT_LEVEL_ENABLED`?

**Review by lukashuebner — APPROVED** [review]

**Comment by lukashuebner** [comment]
I'd prefer `KASSERT_ENABLED` :-) If Demian insists on `KASSERT_LEVEL_ENABLED`, that's also fine with me.

**Comment by DanielSeemaier** [comment]
IMO `KASSERT_ENABLED` is expressive enough

**Comment by Hespian** [comment]
Ok, if you both think it’s expressive enough, it’s fine with me.

but is there no test at all for this?

**Comment by DanielSeemaier** [comment]
> Ok, if you both think it’s expressive enough, it’s fine with me.
> 
> but is there no test at all for this?

added a test

**Review by Hespian — APPROVED** [review]

**Pull request merged**
